"""
Phase 7: Text Generation Pipeline

Provides autoregressive byte-level text generation using the
complete FLUX pipeline: CSE encoding → field query → CGN processing →
output head → byte sampling.
"""

import sys
import time
import torch
import torch.nn.functional as F
from pathlib import Path
from typing import Optional, List, Dict, Any
from dataclasses import dataclass

_PHASES_DIR = Path(__file__).parent.parent
_PROJECT_ROOT = _PHASES_DIR.parent
for _phase in ['phase1', 'phase2', 'phase3', 'phase4', 'phase5', 'phase6']:
    _p = str(_PHASES_DIR / _phase)
    if _p not in sys.path:
        sys.path.insert(0, _p)
if str(_PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(_PROJECT_ROOT))
if str(Path(__file__).parent) not in sys.path:
    sys.path.insert(0, str(Path(__file__).parent))

from flux_model import FLUXModel


# ─────────────────────────────────────────────
# Generation Configuration
# ─────────────────────────────────────────────
GENERATION_CONFIG = {
    'max_length': 200,
    'temperature': 0.8,
    'top_k': 40,
    'top_p': 0.9,
    'repetition_penalty': 1.2,
    'stop_tokens': [0, ord('\n'), ord('.'), ord('!')],
}


@dataclass
class GenerationResult:
    """Result of a text generation call."""
    prompt: str
    generated: str
    full_text: str
    num_bytes_generated: int
    latency_ms: float
    bytes_per_second: float


class TextGenerator:
    """
    Text generation pipeline for the FLUX model.

    Supports multiple decoding strategies:
    - Greedy: always pick most probable byte
    - Sampling: temperature-scaled random sampling
    - Top-K: sample from top K candidates
    - Top-P (nucleus): sample from smallest set summing to P probability
    """

    def __init__(self, model: FLUXModel, config: Optional[Dict[str, Any]] = None):
        self.model = model
        self.config = {**GENERATION_CONFIG, **(config or {})}

    def _top_k_filter(self, logits: torch.Tensor, k: int) -> torch.Tensor:
        """Zero out all logits below the top-k values."""
        if k <= 0:
            return logits
        values, _ = torch.topk(logits, min(k, logits.size(-1)))
        min_val = values[-1]
        return torch.where(logits < min_val, torch.full_like(logits, float('-inf')), logits)

    def _top_p_filter(self, logits: torch.Tensor, p: float) -> torch.Tensor:
        """Zero out logits outside the nucleus (smallest set summing to p)."""
        if p >= 1.0:
            return logits
        sorted_logits, sorted_indices = torch.sort(logits, descending=True)
        cumulative_probs = torch.cumsum(F.softmax(sorted_logits, dim=-1), dim=-1)
        # Remove tokens with cumulative probability above the threshold
        sorted_indices_to_remove = cumulative_probs > p
        # Keep at least one token
        sorted_indices_to_remove[0] = False
        indices_to_remove = sorted_indices[sorted_indices_to_remove]
        logits[indices_to_remove] = float('-inf')
        return logits

    def _apply_repetition_penalty(self, logits: torch.Tensor,
                                   generated: List[int],
                                   penalty: float) -> torch.Tensor:
        """Reduce probability of recently generated bytes."""
        if penalty <= 1.0 or not generated:
            return logits
        recent = set(generated[-50:])  # penalize last 50 bytes
        for byte_val in recent:
            if 0 <= byte_val < logits.size(-1):
                if logits[byte_val] > 0:
                    logits[byte_val] /= penalty
                else:
                    logits[byte_val] *= penalty
        return logits

    def generate(self, prompt: str, max_length: Optional[int] = None,
                 temperature: Optional[float] = None,
                 top_k: Optional[int] = None,
                 top_p: Optional[float] = None,
                 stop_on_newline: bool = False) -> GenerationResult:
        """
        Generate text continuation from a prompt.

        Args:
            prompt: Starting text
            max_length: Override max generation length
            temperature: Override sampling temperature
            top_k: Override top-k filtering
            top_p: Override nucleus sampling threshold
            stop_on_newline: Stop at first newline

        Returns:
            GenerationResult with prompt, generated text, and metrics
        """
        max_len = max_length or self.config['max_length']
        temp = temperature or self.config['temperature']
        k = top_k if top_k is not None else self.config['top_k']
        p = top_p if top_p is not None else self.config['top_p']
        rep_penalty = self.config['repetition_penalty']

        t0 = time.time()

        # Feed prompt through pipeline
        self.model.forward(prompt, learn=False)

        generated_bytes: List[int] = []
        context = prompt

        for step in range(max_len):
            logits = self.model.generate_logits(context)

            # Apply repetition penalty
            logits = self._apply_repetition_penalty(logits, generated_bytes, rep_penalty)

            # Temperature scaling
            logits = logits / max(temp, 1e-8)

            # Top-K filtering
            logits = self._top_k_filter(logits, k)

            # Top-P (nucleus) filtering
            logits = self._top_p_filter(logits, p)

            probs = F.softmax(logits, dim=-1)

            # Sample next byte
            next_byte = torch.multinomial(probs, 1).item()

            # Stop conditions
            if next_byte == 0:
                break
            if stop_on_newline and next_byte == ord('\n'):
                generated_bytes.append(next_byte)
                break

            generated_bytes.append(next_byte)

            # Update context with sliding window
            try:
                all_bytes = list(prompt.encode('utf-8')) + generated_bytes
                context = bytes(all_bytes[-200:]).decode('utf-8', errors='replace')
            except Exception:
                context = bytes(all_bytes[-200:]).decode('latin-1', errors='replace')

        elapsed_ms = (time.time() - t0) * 1000

        try:
            generated_text = bytes(generated_bytes).decode('utf-8', errors='replace')
        except Exception:
            generated_text = bytes(generated_bytes).decode('latin-1', errors='replace')

        full_text = prompt + generated_text
        bps = len(generated_bytes) / max(elapsed_ms / 1000, 1e-8)

        return GenerationResult(
            prompt=prompt,
            generated=generated_text,
            full_text=full_text,
            num_bytes_generated=len(generated_bytes),
            latency_ms=elapsed_ms,
            bytes_per_second=bps,
        )

    def generate_greedy(self, prompt: str, max_length: int = 100) -> GenerationResult:
        """Greedy decoding — always pick the most probable byte."""
        return self.generate(prompt, max_length=max_length, temperature=0.01,
                             top_k=1, top_p=1.0)

    def generate_batch(self, prompts: List[str],
                       max_length: int = 100,
                       temperature: float = 0.8) -> List[GenerationResult]:
        """Generate text for multiple prompts sequentially."""
        return [self.generate(p, max_length=max_length, temperature=temperature)
                for p in prompts]

    def compute_perplexity(self, text: str) -> float:
        """
        Compute byte-level perplexity of a text.

        Perplexity = exp(average negative log-likelihood per byte).
        Lower is better.

        Args:
            text: Text to evaluate

        Returns:
            Perplexity score (float)
        """
        text_bytes = list(text.encode('utf-8'))
        if len(text_bytes) < 2:
            return float('inf')

        total_nll = 0.0
        count = 0

        # Build up context byte by byte
        for i in range(1, len(text_bytes)):
            # Context up to byte i
            try:
                context = bytes(text_bytes[:i]).decode('utf-8', errors='replace')
            except Exception:
                context = bytes(text_bytes[:i]).decode('latin-1', errors='replace')

            logits = self.model.generate_logits(context)
            log_probs = F.log_softmax(logits, dim=-1)

            target_byte = text_bytes[i]
            if 0 <= target_byte < log_probs.size(-1):
                total_nll -= log_probs[target_byte].item()
                count += 1

        if count == 0:
            return float('inf')

        avg_nll = total_nll / count
        import math
        return math.exp(avg_nll)
